######################################################################
##
## Filename: vga_640x480_tb.udo
## Created on: Tue Jul 30 20:55:59 RTZ 2 (зима) 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
